### ISSUE TITLE
Binwalk not working (High priority)

### ISSUE THREAD

**Issue by Jonty16117** [compsecdirect/autodyne#4]
When the container (autodyne-em1) is started, I see the following error. I did some investigation, and it looks like the file `fw_dev_data/firmware-analysis-toolkit/firmadyne/sources/extractor/extractor.py` is unable to extract *.bin image into the tar and place it in the `/opt/firmadyne/images/*.tar.gz` dir. And this might be due to the python versions issue. As the default python in the container is python2, it is unable to run this script using python2. Without this, nothing will work, please help resolving it. I will try my best on what I can do. Thanks and following is the traceback:

```
 *  Executing task in folder testenvironment: docker logs --tail 1000 -f 0459631a829f1d84ba5c1d9f8965a38ac893a6d9233ef589c0b750e2213ba14c 

+ export PGPASSWORD=firmadyne
+ PGPASSWORD=firmadyne
+ export USER=firmadyne
+ USER=firmadyne
+ sleep 5
+ '[' '!' -z '' ']'
+ exec /opt/firmadyne/autodyne-0.5a.sh netgear 1.bin
+ socat TCP-LISTEN:5432,fork TCP:172.21.0.2:5432
Changing Directory...
Setting netgear for /opt/firmadyne/samples/1.bin
Here is basename 1.bin
>> Database Image ID: 1

/opt/firmadyne/samples/1.bin
>> MD5: 904d495563ba7c21a0478777b33fd11d
>> Tag: 1
>> Temp: /tmp/tmp3XnvHT
>> Status: Kernel: True, Rootfs: False, Do_Kernel: False,                 Do_Rootfs: True
>> Recursing into archive ...
>> Recursing into compressed ...
>> Cleaning up /tmp/tmp3XnvHT...
tar: /opt/firmadyne/images/1.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: /opt/firmadyne/images/1.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: /opt/firmadyne/images/1.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
ImageID: 1
Arch: default architecture guessed
mipseb
Extracting filesystem and building QEMU image for sample 1...
Traceback (most recent call last):
  File "./scripts/tar2db.py", line 101, in <module>
    main()
  File "./scripts/tar2db.py", line 98, in main
    process(iid, infile)
  File "./scripts/tar2db.py", line 69, in process
    (files, links) = getFileHashes(infile)
  File "./scripts/tar2db.py", line 12, in getFileHashes
    t = tarfile.open(infile)
  File "/usr/lib/python3.6/tarfile.py", line 1573, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1638, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/usr/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/opt/firmadyne/images/1.tar.gz'
starting emulator for sample 1...
```

**Comment by Jonty16117** [comment]
@compsecdirect hi, can you please help me resolve this python deps issue

**Comment by Jonty16117** [comment]
@compsecdirect anything please?

**Comment by compsecdirect** [comment]
We can't really troubleshoot issues like these without more context, like which firmware image is used.   
If you exec into the docker image, and run /opt/firmadyne/autodyne-0.5a.sh netgear 1.bin after placing the 1.bin into the samples folder; what is the output of that and which firmware file are you using, with a download location?

We also see similar issues with this project, but please don't spam comments in issues requesting help as the initial issue is sufficient.

**Comment by Jonty16117** [comment]
My apologies, but the issue seemed like it was a wrong samples-out dir and the python version issue. But fixed the issue once and for all by making the samples and samples-out dir automatically generated and fixed the python version issue too: https://github.com/compsecdirect/autodyne/pull/2
